name: dart_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  grpc: ^3.2.4
  meta: ^1.11.0
  protobuf: ^3.1.0
  protobuf_wellknown: ^0.1.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
